apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:LuanCristopher/GitOps-EzOps.git
    targetRevision: main
    path: charts/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: ezops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
