apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
