replicaCount: 2

image:
  repository: 654654369899.dkr.ecr.us-east-1.amazonaws.com/ezops-backend
  tag: "latest"   # será trocado pela pipeline
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: luanoliveira-backend.exam.ezopscloud.tech
