replicaCount: 2

image:
  repository: 654654369899.dkr.ecr.us-east-1.amazonaws.com/luan-test-backend
  # a tag será substituída na pipeline pelo hash do commit
  tag: "<COMMIT_HASH>"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8080
  type: ClusterIP


envFromSecret: backend-db

targetGroupArn: "arn:aws:elasticloadbalancing:us-east-1:654654369899:targetgroup/luan-test-tg/3df1444ba2975bcf"
